name: Build OAPI

on:
  push:
    paths:
      - 'ncentral-api.json'

jobs:
  build-oapi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run build script
        run: ./build.sh
        with:
          working-directory: .github/workflows

      - name: Go formatting
        run: |
          gofmt -w ./

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --cached --quiet || git commit -m "Automagic API generation: update from cw-api.json"
          git push